.gitignore
TestScripts/C Tests.win/CTests.sln
TestScripts/C Tests.win/CTests.vcxproj
TestScripts/C Tests.win/CTests.vcxproj.filters
TestScripts/C Tests.win/CTests.vcxproj.user
TestScripts/C Tests/main.c

- Added a Visual Studio solution that builds the C test scripts on Windows.
- Updated .gitignore to ignore user specific Visual Studio files
- Updated .gitignore to ignore Windows build folders
- Fixed a bug in closeTest. It now properly closes the UDP port a second time after reopening the port to verify that it closed successfully.
On Windows, the failure to close the port in closeTest caused sendReadTest to fail since it reused port 49063. The fact that this doesn't seem to happen on Mac indicates that perhaps re-opening the port in closeTest isn't a perfect test that the port was successfully closed.

Added Visual Studio solution for C test scripts and fixed test bug

---

C/xpcExample/xpcExample.win/xpcExample.sln
C/xpcExample/xpcExample.win/xpcExample.vcxproj
C/xpcExample/xpcExample.win/xpcExample.vcxproj.filters
C/xpcExample/xpcExample/src/main.cpp
MATLAB/+XPlaneConnect/sendCTRL.m
MATLAB/Example/Example.m
TestScripts/C Tests/main.c
TestScripts/CPP Tests/main.cpp

- Added Visual Studio solution for C client example.
- Fixed inconsistent indentation in C client example.
- Changed default behavior in MATLAB client's sendCTRL function to leave unchanged instead of setting default values.
- Fixed sendPOSI and sendDATA sections of the MATLAB example.
- Fixed port number in the C and C++ setCONN tests.

Several small fixes

---

MATLAB/+XPlaneConnect/pauseSim.m
MATLAB/+XPlaneConnect/readUDP.m
MATLAB/+XPlaneConnect/requestDREF.m
MATLAB/+XPlaneConnect/setConn.m
TestScripts/MATLAB Tests/setConnTest.m

- setCONN is functional, although it should probably be revisited at some point to see if the same functionality can be achieved without using globals
- pauseSim now sends the same number of bytes as its C sibling.

Fixed setCONN and tweaked pauseSim in MATLAB client

---

C/src/xplaneConnect.c

sendText using the number 40 instead of message length in sendUDP call.
Messages would be cut off if longer than this

Fix sendTEXT bug

---

xpcPlugin/XPCPlugin.cpp

This one uses a header instead of pointer galore for this ambiguity issue.

fix osx ambiguity

---

.gitignore
xpcPlugin/MessageHandlers.cpp
xpcPlugin/MessageHandlers.h

This PR enables to control the location and zoom of the runway camera to simulate a remotely controlled aircraft piloting experience.
If an extended view message is received, the view is switched to runway view and the camera is placed at the coordinates specified in the message, pointing at the aircraft in pitch and yaw.
Default behaviour with the standard view message ensures compatibility with existing software.

Runway camera location control

---

xpcPlugin/CMakeLists.txt
xpcPlugin/MessageHandlers.cpp
xpcPlugin/MessageHandlers.h
xpcPlugin/Timer.cpp
xpcPlugin/Timer.h
xpcPlugin/UDPSocket.cpp
xpcPlugin/UDPSocket.h
xpcPlugin/XPCPlugin.cpp
xpcPlugin/xpcPlugin.xcodeproj/project.pbxproj
xpcPlugin/xpcPlugin/xpcPlugin.vcxproj

Hi, 
as discussed in https://github.com/nasa/XPlaneConnect/issues/147, here is the implementation of the UDP discovery of the plugin.
The format of the UDP packet is:
```
4 bytes: BECN
1 byte: 0
2 bytes: XPlaneConnect server port e.g. '49009'
4 bytes: X-Plane version e.g. '11260'
null terminated string: XPlaneConnect plugin version e.g. '1.3-rc.1'
```
The changes are
- Use `C++11` needed by `<thread>`
- Added a helper `Timer` class that can run a callback every x milliseconds
- Start a timer in `XPluginEnable` to UDP multicast the `BECN` packet
Compiles fine on all platforms. I'll provide the binaries once this is reviewed.
What is not part of this pull request are the client side implementations but I believe this can be done separately.
Tested on macOS, Linux and Windows

Added UDP multicast for plugin discovery

---

Java/.idea/misc.xml
Java/.idea/modules.xml
Java/Examples/BasicOperation/src/Main.java
Java/Examples/DiscoveryExample/DiscoveryExample.iml
Java/Examples/DiscoveryExample/src/DiscoveryConnectionExample.java
Java/Examples/DiscoveryExample/src/SimpleDiscoveryExample.java
Java/XPlaneConnect.iml
Java/src/XPlaneConnect.java
Java/src/discovery/Beacon.java
Java/src/discovery/BeaconParser.java
Java/src/discovery/BeaconReceivedListener.java
Java/src/discovery/DiscoveryConnectionCallback.java
Java/src/discovery/XPlaneConnectDiscovery.java
TestScripts/Java Tests/XPlaneDiscoveryTests.java

Client side Java implementation of the BECN discovery. Server side is implemented in https://github.com/nasa/XPlaneConnect/pull/153
```java
XPlaneConnectDiscovery discovery = new XPlaneConnectDiscovery();
discovery.onBeaconReceived(beacon -> {
System.out.println("Discovered XPlaneConnect plugin:");
System.out.println("Plugin version: " + beacon.getPluginVersion());
System.out.println("X-Plane version: " + beacon.getXplaneVersion());
System.out.println("Address: " + beacon.getXplaneAddress().getHostAddress() + ":" + beacon.getPluginPort());
});
discovery.start();
```
The PR also includes a helper to automatically instantiate a `XPlaneConnect` with the discovered plugin:
```
XPlaneConnectDiscovery discovery = new XPlaneConnectDiscovery();
discovery.start(xpc -> {
// use the XPlaneConnect …
```

Java client BECN implementation

---

README.md

I've been testing the currently available pre-built binaries on X-Plane 11 and they seem to work perfectly fine out of the box. For testing purpose I used a Python client.

Added X-Plane 11 compatibility to README

---

xpcPlugin/xpcPlugin/xpcPlugin.vcxproj

A wrong `Timer.h` file type in Visual Studio was causing linker errors.
fix #166

Fixed Timer.h Visual Studio Item Type

---

azure-pipelines.yml

Azure pipelines releases will now be created as drafts so that I can edit the title and release notes before publishing.

Make azure pipelines create draft releases

---

xpcPlugin/DataManager.cpp
xpcPlugin/Message.cpp
xpcPlugin/MessageHandlers.cpp

- Add check to `SetPosition` to return early if all values are defaults. (This might happen with a POSI command that specifies orientations but not positions)
- Add check to `SetOrientation` to return  early if all values are defaults
- Fix a bug in `HandlePosi` where the gear value was being read incorrectly
- Also updates the syntax for the position copy to something that's ARM compatible
- Fixes the code in `Message` to print the value of the POSI command

POSI fixes

---

.gitignore
azure-pipelines.yml
xpcPlugin/Message.cpp
xpcPlugin/MessageHandlers.cpp
xpcPlugin/MessageHandlers.h
xpcPlugin/xpcPlugin.xcodeproj/project.pbxproj

This adds the capability to obtain the terrain height above MSL at a given location using a XPLM terrain probe. A new message pair (GETT query, terrain response) was added to specify the probe location and to return the data.
The probe is persistent once created for speed. Currently only one probe is supported.
Using this mechanism allows to land an aircraft onto the x-plane world.
Definitions for the message formats will be added shortly.

Terrain height probe

---

C/monitorExample/main.c
C/playbackExample/src/playback.c
C/src/xplaneConnect.c
C/src/xplaneConnect.h
Python3/src/basicExample.py
Python3/src/monitorExample.py
Python3/src/playbackExample.py
Python3/src/xpc.py
TestScripts/C Tests/CtrlTests.h
TestScripts/C Tests/DataTests.h
TestScripts/C Tests/DrefTests.h
TestScripts/C Tests/PosiTests.h
TestScripts/Python3 Tests/Tests.py
TestScripts/Python3 Tests/Tests.pyproj
xpcPlugin/MessageHandlers.cpp

Issues #180, #181, and #189 all discuss the problem of precision in receiving Latitude, Longitude, and Altitude from X-Plane using getPOSI.  sendPOSI does provide for double Lat/Lon/Alt, but getPOSI was still using float.  This pull request includes the required getPOSI fixes for the xpcPlugin, the C examples, the Python3 examples, and the C TestScripts.  New Python3 test scripts have been added.  These fixes maintain backwards compatibility with previous xpcPlugin and getPOSI by still being able to interpret the previous UDP packet formats, but without the better precision.  I did not fix the Python, Java, or Matlab examples or tests.  There are also additional bug fixes included to eliminate compiler errors and warnings I was receiving when building using the MSYS2 mingw-w64 gcc …

Double Lat/Lon/Alt for getPOSI

---

C/src/xplaneConnect.c
C/src/xplaneConnect.h
xpcPlugin/MessageHandlers.cpp
xpcPlugin/MessageHandlers.h

Improved the accuracy of the HandleGetT message handler in the plugin to work better in areas of high elevation far from the scenery origin.  Used the method outlined by Ben Supnik in this forum post:
[https://forums.x-plane.org/index.php?/forums/topic/38688-how-do-i-use-xplmprobeterrainxyz/&page=2](url)
Also expanded the data that is sent back via the TERR UDP packet to include the velocity vector of the terrain.  This may be useful to people programming a gear reaction model for an airplane landing on the aircraft carrier.
Finally, created a getTERR function in the C library so that people can request and receive the terrain probe data.

Improved MessageHandler HandleGetT and created getTERR C function

---

C/src/xplaneConnect.c
C/src/xplaneConnect.h
xpcPlugin/Message.cpp
xpcPlugin/MessageHandlers.cpp
xpcPlugin/MessageHandlers.h

In simulation environments using X-Plane as a visual system, the user will need to use sendPOSI to move the aircraft in X-Plane, but will also need to use getTERR to return the height of the terrain below the aircraft for landing gear reaction modeling.  It is very useful to be able to do this in one step, so have created the sendPOST function that combines sendPOSI with getTERR.  sendPOST sends a POST UDP message, which has exactly the same format as the POSI UDP message, just with a POST header.  The plugin has been modified to interpret this message, position the airplane in the same way as sendPOSI, and then return a TERR UDP message.  sendPOST then reads the TERR message and provides the terrain information to the user.

Created sendPOST function that combines functions of sendPOSI and getTERR

---

C/src/xplaneConnect.c
xpcPlugin/UDPSocket.cpp
xpcPlugin/UDPSocket.h

In the xplaneConnect.c sendUDP and readUDP functions, longer than necessary socket timeouts were being used.  They were also different for Windows and Linux/Mac.  These socket timeouts contribute to process time delay and potential stuttering.  The timeouts are now minimized based on testing with the Example and Test programs.  They are also standardized for all operating systems.
Line 209 of xplaneConnect.c has a TO DO comment for a potential future upgrade.  If the xplaneConnect.c functions had message handlers like the plugin, then the socket timeout of the readUDP function could be set to 0 to make the read polling.  The process would not need to wait around for a read to complete.  It could move on to other tasks and read and process the UDP messages as they arrive.
In the plugin …

  Minimize Send and Receive Socket Timeout Delays

---

Python3/src/xpc.py

`readDATA` method uses `range` which requires the argument to be an integer (`'float' object cannot be interpreted as an integer`). `rows` is calculated by dividing the length of the buffer -5 by 36. Division in python 3 returns a float. By using integer division (`//` instead of `/`), the `rows` variable will be an int which will not cause this exception.

python3 integer division issue

---

xpcPlugin/DataManager.cpp
xpcPlugin/DataManager.h
xpcPlugin/MessageHandlers.cpp
xpcPlugin/MessageHandlers.h

I added two new commands to the plugin: **BCOM** (begin command) and **ECOM** (end command). These take the same data format as the existing COMM command. These call the X-Plane SDK's `XPLMCommandBegin` and `XPLMCommandEnd` functions respectively, which allow you to independently trigger and end a command (allowing you to "hold down a button"). 
The data manager also explicitly tracks commands sent to X-Plane to ensure that only commands that have been explicitly started by `XPLMCommandBegin` can be ended by `XPLMCommandEnd` (a requirement of the X-Plane SDK). I also renamed `DataManager::Execute()` to `DataManager::MomentaryCommand()` for clarity and consistency with `DataManager::BeginCommand()` and `DataManager::EndCommand()`.

Added BCOM/ECOM commands to enable support of beginning/ending X-Plane commands

---

xpcPlugin/CMakeLists.txt

The file `CameraCallbacks.cpp` is missing in the `CMakeLists.txt` and the generated binary on Linux has an undefined symbol (the release file is also affected).
This is (probably) the same problem that caused this issue: #239

[Build] CameraCallbacks.cpp is missing in CMakeLists.txt
